name: "Continous deployment"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "cloning repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
